version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1 # Invoke the Heroku orb

jobs:
  build:
    docker:
      - image: circleci/python:3.8.9
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            mkdir ../trazy_analysis
            mv * ../trazy_analysis
            mv ../trazy_analysis .
            cd trazy_analysis
            wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
            tar -xzf ta-lib-0.4.0-src.tar.gz
            cd ta-lib/
            ./configure --prefix=/usr
            make
            sudo make install
            cd ..
            python3.8 -m venv venv
            . venv/bin/activate
            python3.8 -m pip install --upgrade pip
            python3.8 -m pip install -r requirements.txt
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "trazy_analysis/requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            pwd
            cd trazy_analysis
            . venv/bin/activate
            cd ..
            mkdir trazy-analysis-test-reports
            python3 -m pytest &> trazy-analysis-test-reports/tests.log
      - store_artifacts:
          path: /home/circleci/project/trazy_analysis/trazy-analysis-test-reports
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large

workflows:
  version: 2.1
  heroku_deploy:
    jobs:
      - build:
          context: heroku_analysis_dev
