version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1 # Invoke the Heroku orb

jobs:
  build:
    docker:
      - image: circleci/python:3.8.9
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            sudo apt-get install python3-dev
            python3.8 -m venv venv
            . venv/bin/activate
            pip3.8 install --upgrade pip
            pip3.8 install -r requirements.txt
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            mkdir trazy-analysis-test-reports
            python -m pytest &> trazy-analysis-test-reports/tests.log
      - store_artifacts:
          path: /home/circleci/project/trazy-analysis-test-reports

workflows:
  version: 2.1
  heroku_deploy:
    jobs:
      - build:
          context: heroku_analysis_dev
