version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1 # Invoke the Heroku orb

jobs:
  build:
    docker:
      - image: circleci/python:3.8.9
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            cd ..
            mkdir trazy_analysis
            mv project/* trazy_analysis
            cd trazy_analysis
            wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
            tar -xzf ta-lib-0.4.0-src.tar.gz
            cd ta-lib/
            ./configure --prefix=/usr
            make
            sudo make install
            cd ..
            python3.8 -m venv venv
            . venv/bin/activate
            pip3.8 install --upgrade pip
            pip3.8 install -r requirements.txt
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pwd
            ls
            mkdir trazy-analysis-test-reports
            python3 -m pytest &> trazy-analysis-test-reports/tests.log
      - store_artifacts:
          path: /home/circleci/project/trazy-analysis-test-reports

workflows:
  version: 2.1
  heroku_deploy:
    jobs:
      - build:
          context: heroku_analysis_dev
