version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1 # Invoke the Heroku orb

jobs:
  build:
    docker:
      - image: circleci/python:3.8.9
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            mkdir ../trazy_analysis
            mv * ../trazy_analysis
            mv ../trazy_analysis .
            cd trazy_analysis
            wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
            tar -xzf ta-lib-0.4.0-src.tar.gz
            cd ta-lib/
            ./configure --prefix=/usr
            make
            sudo make install
            cd ..
            python3.8 -m venv venv
            . venv/bin/activate
            python3.8 -m pip install --upgrade pip
            python3.8 -m pip install -r requirements.txt
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "trazy_analysis/requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            pwd
            cd trazy_analysis
            . venv/bin/activate
            cd ..
            mkdir trazy-analysis-test-reports
            python3 -m pytest -vvs
      - store_artifacts:
          path: /home/circleci/project/trazy_analysis/trazy-analysis-test-reports

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
          context: trazy_dev
