# Generated by Django 2.2.12 on 2020-05-16 14:16

import actionsapi.models.models
from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[(actionsapi.models.models.ActionType(('BUY',)), 'BUY'), (actionsapi.models.models.ActionType('SELL'), 'SELL')], default=actionsapi.models.models.ActionType(('BUY',)), max_length=4)),
                ('position_type', models.CharField(choices=[(actionsapi.models.models.PositionType(('LONG',)), 'LONG'), (actionsapi.models.models.PositionType('SHORT'), 'SHORT')], default=actionsapi.models.models.PositionType(('LONG',)), max_length=5)),
                ('amount', models.IntegerField(default=1)),
                ('confidence_level', models.DecimalField(decimal_places=3, max_digits=4)),
                ('strategy', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('candle_id', models.BigIntegerField(null=True)),
                ('parameters', jsonfield.fields.JSONField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time at which the action needs to be taken')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='DUMMY_SYMBOL', max_length=200)),
                ('open', models.DecimalField(decimal_places=5, max_digits=13)),
                ('high', models.DecimalField(decimal_places=5, max_digits=13)),
                ('low', models.DecimalField(decimal_places=5, max_digits=13)),
                ('close', models.DecimalField(decimal_places=5, max_digits=13)),
                ('volume', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of the candle')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='candle',
            constraint=models.UniqueConstraint(fields=('timestamp', 'symbol'), name='candles_unique_identifier'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['parameters'], name='parameters_index'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.UniqueConstraint(fields=('timestamp', 'symbol', 'strategy'), name='actions_unique_identifier'),
        ),
    ]
